import '../styles/global.css';
import Head from 'next/head';
import Link from 'next/link';
export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,500;0,700;1,300;1,700&display=swap" rel="stylesheet" />
      </head>
      <body style={{ fontFamily: 'Work Sans' }}>
        <div className="main-wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}
